# Generated by Django 4.1.13 on 2024-08-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetsessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AddField(
            model_name='student',
            name='phonenumber',
            field=models.CharField(default='', max_length=15),
        ),
    ]
