# Generated by Django 4.1.13 on 2024-09-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetsessions', '0002_remove_student_age_student_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
