# Generated by Django 4.1.13 on 2024-08-30 07:56

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('userEmail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('token', djongo.models.fields.JSONField()),
            ],
        ),
    ]
