# Generated by Django 4.1.13 on 2024-08-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_credentials_delete_googleoauth2credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_uri', models.URLField()),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('scopes', models.JSONField()),
                ('expiry', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Credentials',
        ),
    ]
