# Generated by Django 4.1.13 on 2024-08-14 08:08

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_usercredentials_delete_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.EmailField(max_length=254)),
                ('token', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserCredentials',
        ),
    ]
